spring:
  neo4j:
    uri: ${NEO4J_URI:bolt://localhost:7687}
    authentication:
      username: ${NEO4J_USER:neo4j}
      password: ${NEO4J_PASS:password}
    pool:
      max-connection-pool-size: 50
      connection-acquisition-timeout: 60s
  data:
    neo4j:
      database: neo4j
  jackson:
    serialization:
      INDENT_OUTPUT: true

server:
  port: 8080

logging:
  level:
    org.springframework.data.neo4j: INFO
    com.devmh.graphs: DEBUG

graphs:
  search:
    fulltext:
      enabled: true
      indexName: ft_node_all
      labels: Case,Docket,Person,Judge,Lawyer
      properties: name,number,court,firm
